### ISSUE TITLE
Can't parse results with numerical instability

### ISSUE THREAD

**Issue by axxroytovu** [astronomeralex/galfit-python-parser#3]
When Galfit finds numerical instability, the results are surrounded by asterisks, e.g. \*43.2\*. This crashes the read function.

**Comment by astronomeralex** [comment]
@axxroytovu thanks for reporting this. could you post the error you get?

**Comment by axxroytovu** [comment]
I get this:
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "galfit_parser.py", line 105, in __init__`
`    setattr(self,"component_" + str(i),GalfitComponent(galfitheader,i))`
`  File "galfit_parser.py", line 43, in __init__`
`    setattr(self,paramsplit[1].lower(),float(val[0]))`
`ValueError: could not convert string to float: *19.9969*`

I fixed it by replacing lines 38 through 44 with:
`                val = val.translate(None,'[]')`
`                setattr(self,paramsplit[1].lower(),float(val.translate(None, '*')))`
`                setattr(self,paramsplit[1].lower() + '_err',None)`
`            else:              #normal variable parameter`
`                val = val.split()`
`                setattr(self,paramsplit[1].lower(),float(val[0].translate(None, '*')))`
`                setattr(self,paramsplit[1].lower() + '_err',float(val[2].translate(None, '*')))`

which seems like a bit of a jurry-rigged solution.

**Comment by astronomeralex** [comment]
thanks! this does seems a bit jury-rigged. perhaps a better solution would be to use a try except statement to catch the ValueError? Also, this should definitely trigger the code to print out a warning. Could you make those changes and submit a pull request?

**Comment by astronomeralex** [comment]
close with pull request #4
